apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jmeter-master-server.fullname" . }}-server
  labels:
    {{- include "jmeter-master-server.labels" . | nindent 4 }}
spec:
  replicas: {{  .Values.jmeter.server.replicaCount  }}
  selector:
    matchLabels:
      {{- include "jmeter-master-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jmeter-master-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jmeter-master-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: jmeter-server
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jmeter-svr-port
              containerPort: 1099
              protocol: TCP
            - name: jmeter-rmi-port
              containerPort: 50000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
